import keymirror from 'keymirror';

export default keymirror({
  RETRIEVE_MOVIES_GENRES_SUCCESS: null,
  RETRIEVE_POPULAR_MOVIES_SUCCESS: null,
  RETRIEVE_NOWPLAYING_MOVIES_SUCCESS: null,
  RETRIEVE_MOVIES_LIST_SUCCESS: null,
  RETRIEVE_MOVIE_DETAILS_SUCCESS: null,
  RETRIEVE_MOVIES_SEARCH_RESULT_SUCCESS: null,

  GET_CLUBS_REQUEST: null,
  GET_CLUBS_SUCCESS: null,
  GET_CLUBS_FAILURE: null,

  GET_CLUB_DETAIL_REQUEST: null,
  GET_CLUB_DETAIL_SUCCESS: null,
  GET_CLUB_DETAIL_FAILURE: null,
});
